name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      TEST_DATA_PATH: src/tests/test-data/standard-user-data.json
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.12.1'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Sanity Tests
        run: npm run "Sanity Tests"
      - uses: actions/upload-artifact@v2 
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
